### PR TITLE
Yoga_Template 2

### PR DESCRIPTION
**Pull request by SAHU-01**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue no.)

#130 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ * ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [* ] My code follows the style guidelines of this project
- [ *] I have performed a self-review of my own code
- [ *] I have commented my code, particularly in hard-to-understand areas
- [ *] I have made corresponding changes to the documentation
- [ *] My changes generate no new warnings
- [ *] I have added tests that prove my fix is effective or that my feature works
- [ *] New and existing unit tests pass locally with my changes
- [ *] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by arpit456jain** [comment]
@Sanju-github002 update your branch

Its showing changes in previous yoga template too

**Comment by SAHU-01** [comment]
> @Sanju-github002 update your branch
> 
> Its showing changes in previous yoga template too

give me a minute I'll check and resolve the issues

**Comment by SAHU-01** [comment]
yes I fixed the hero section of the previous template last night ,because the existent image seemed a bit not going with the text so i adjusted the size and made some minor changes,if you insist on not having those changes,I'll revert them or you can close this pr,I'll fix things and make a new commit altogether!

**Comment by arpit456jain** [comment]
@SAHU-01 do one thing rebase your branch and merge the current master branch to your branch then pull the changes to your local system and then push it...

Make a new pr after updating your master branch

**Comment by SAHU-01** [comment]
> @SAHU-01 do one thing rebase your branch and merge the current master branch to your branch then pull the changes to your local system and then push it...
> 
> Make a new pr after updating your master branch

sure I'll do that right away!

**Comment by arpit456jain** [comment]
yes @SAHU-01 now its ok just need 2 things

Add 
1. path in json file 
2. add a ss of your template and name it preiew.png

**Comment by arpit456jain** [comment]
and yeah just a tip 

in PR description  you have to add a x instead of * 
i mean lie this [x] not [*] or you can check them after making PR

**Comment by arpit456jain** [comment]
and Always link your PR with issue like this 
Fixes : #132

**Comment by SAHU-01** [comment]
> yes @SAHU-01 now its ok just need 2 things
> 
> Add
> 
> 1. path in json file
> 2. add a ss of your template and name it preiew.png

I have made the changes,should I close this pr and make  a new pr ?

**Pull request merged**
