### PR TITLE
Added Preview Images

### LINKED ISSUE #96: Arrange cards in Alphabatical order (style_link.json)
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### LINKED ISSUE #105: link preview images in home page
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by jigar-sable**
# Description

Added preview of each template. Code according to the deployment of this repo. 

Fixes #105 
Fixes #96 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
This will work on GH Pages/Netlify deploy of this repo. After merging you will definitely see all those changes.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@jigar-sable please check once 
https://deploy-preview-106--cool-front-end-templates.netlify.app/

**Comment by arpit456jain** [comment]
@jigar-sable please check it once 
https://deploy-preview-106--cool-front-end-templates.netlify.app/

**Comment by jigar-sable** [comment]
@arpit456jain I know deploy preview will not work. That's what I mention above after merging this PR. It will definitely work as coded according to the post deployment.

**Comment by arpit456jain** [comment]
@jigar-sable can't we use direct URL of images instead of GitHub

**Comment by arpit456jain** [comment]
> @arpit456jain I know deploy preview will not work. That's what I mention above after merging this PR. It will definitely work as coded according to the post deployment.

yeah i got that that's why i deleted the comment can we use direct urls it will be better because due to plagiarism my github pages got blocked 2 times before

**Comment by jigar-sable** [comment]
Okay but that's nothing link related to GH Pages. It will work anywhere you deploy.
`https://raw.githubusercontent.com/arpit456jain`  base url

**Comment by arpit456jain** [comment]
> Okay but that's nothing link related to GH Pages. It will work anywhere you deploy.
> `https://raw.githubusercontent.com/arpit456jain` base url. I did this as this was the most efficient way per templates so just merge and see the changes once.

ok lets try

**Review by ankitapuri — APPROVED** [review]

**Comment by ankitapuri** [comment]
@arpit456jain u can merge

**Pull request merged**
