### PR TITLE
Added Obatin - Medicine Landing Page

### LINKED ISSUE #62: Obatin - Medicine Landing Page
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Possible solution**

- I would like to add a medicine landing page named Obatin. This webpage was inspired by a dribble mockup design.

### PR DESCRIPTION
**Pull request by kiruba-r11**
# Description

Obatin is a Medicine Landing Page. It is responsive and built using HTML, CSS, and Bootstrap

Fixes #62 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by arpit456jain** [comment]
@kiruba-r11 kindly share some ss or videos if possible

**Comment by arpit456jain** [comment]
@kiruba-r11 try to resove these merge conflicts please

**Comment by kiruba-r11** [comment]
@arpit456jain Below are the screenshots

Screenshot 2021-07-15 at 11 31 38 AM
Screenshot 2021-07-15 at 11 31 52 AM
Screenshot 2021-07-15 at 11 32 05 AM
Screenshot 2021-07-15 at 11 32 18 AM
Screenshot 2021-07-15 at 11 32 29 AM

**Review by ankitapuri — APPROVED** [review]

**Comment by ankitapuri** [comment]
@arpit456jain u can merge it

**Pull request merged**
