### PR TITLE
Create Footer in Food ordering website 

### PR DESCRIPTION
**Pull request by Sanju-github002**
Fixed issue #56 

Make a responsive Footer in food ordering website. Pls check it once 

Screenshot 2021-07-14 105915
Screenshot 2021-07-14 111407

### CODE REVIEW

**Comment by arpit456jain** [comment]
@ankitapuri please review

**Comment by ankitapuri** [comment]
> @ankitapuri please review

okay

**Comment by ankitapuri** [comment]
The image is not visible in the background , it shows just white color 
image

**Comment by Sanju-github002** [comment]
> The image is not visible in the background , it shows just white color
> image

yes I gone close this PR and sent other in which I solve this issue also

**Pull request closed without merging**
