### PR TITLE
Improve yoga templates(#99)

### LINKED ISSUE #99: Improve Yoga Template
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by Skapsime**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #99 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
 update UI of yoga templates(#99)

### CODE REVIEW

**Comment by arpit456jain** [comment]
good work @Skapsime 

please update your PR description and link your issue  like Fixes : #no_of_your_issue

**Review by ankitapuri — APPROVED** [review]

**Comment by ankitapuri** [comment]
@Skapsime just correct the PR template rest is good 
@arpit456jain then u can merge

**Comment by Skapsime** [comment]
can you please help me how to correct this

**Comment by arpit456jain** [comment]
yes @Skapsime you can see 3 dots on the top of PR description

**Comment by arpit456jain** [comment]
image

click on edit and make changes

**Comment by Skapsime** [comment]
yes i got it and then next?

**Comment by Skapsime** [comment]
Done

**Comment by arpit456jain** [comment]
Replace 
Fixes # (issue no.) 
to
`Fixes  : #99`

**Comment by ankitapuri** [comment]
> yes i got it and then next?

Click on edit and then just provide a description of what work u have done and also to fix issue add the issue number after the # to link it

**Comment by arpit456jain** [comment]
@Skapsime still its not linked but no problem try to do it from next time

**Comment by Skapsime** [comment]
okay, Thanks

**Comment by arpit456jain** [comment]
> > yes i got it and then next?
> 
> Click on edit and then just provide a description of what work u have done and also to fix issue add the issue number after the # to link it

yes @Skapsime this is also important I know u r a beginner that's why its fine take ur time but always try do information as much as possible

**Comment by Skapsime** [comment]
okay thank you  for help

**Pull request merged**
