### PR TITLE
Added Glassmorphic Profile Card

### LINKED ISSUE #70: Glassmorphic Profile Card
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Possible solution**

It is a glassmorphic profile card, which can be used to describe us, our skills, and our achievements.

## **Screenshots**
Screenshot 2021-07-15 at 12 19 49 PM

### PR DESCRIPTION
**Pull request by kiruba-r11**
# Description

Added Glassmorphic Profile Card.

Fixes #70 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

## **Screenshots**
Screenshot 2021-07-15 at 12 19 49 PM

### CODE REVIEW

**Comment by ankitapuri** [comment]
Send screenshots too

**Comment by kiruba-r11** [comment]
@ankitapuri I have updated with screenshots

**Comment by arpit456jain** [comment]
@kiruba-r11 please share some screenshots how its looking when you made...
And i hope its made by you not downloaded from anywhere because it leads to palagrism

**Review by ankitapuri — APPROVED** [review]

**Comment by ankitapuri** [comment]
@arpit456jain u can merge it 
This is really great @kiruba-r11 🎉

**Comment by kiruba-r11** [comment]
@arpit456jain Yes, I have made it on my own, even added few AOS animations to it too

**Pull request merged**
