### PR TITLE
Updated Home Page UI

### LINKED ISSUE #97: Improve UI of home page
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by jigar-sable**
# Description
Card design update with preview image of each templates. Added hover effects.

Fixes #97 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
cfet

### CODE REVIEW

**Comment by arpit456jain** [comment]
https://deploy-preview-104--cool-front-end-templates.netlify.app/?utm_source=github&utm_campaign=bot_dp

@jigar-sable images are not visible

**Comment by jigar-sable** [comment]
@arpit456jain I haven't added preview links of all templates in json file.

**Comment by arpit456jain** [comment]
ok @jigar-sable so you are adding in this PR or you will do this in another one ?

**Comment by jigar-sable** [comment]
Sure, will create another issue for that.

**Pull request merged**
