### PR TITLE
Update change in Gym website

### PR DESCRIPTION
**Pull request by Sanju-github002**
I add a footer where are link of social media and small details of website 
I fixed issue #69 

Fully responsive footer 

Here some images -
Screenshot 2021-07-15 141255
Screenshot 2021-07-15 141324
Screenshot 2021-07-15 141348

### CODE REVIEW

**Comment by arpit456jain** [comment]
@Sanju-github002 can you make some chages
1. Background image should not repeat
2. change the heading "Aj ka gym" to some cool heading you like

**Comment by Sanju-github002** [comment]
> @Sanju-github002 can you make some chages
> 
> 1. Background image should not repeat
> 2. change the heading "Aj ka gym" to some cool heading you like

okay I do this changes and make new PR

**Comment by ankitapuri** [comment]
@Sanju-github002 u always don't need to make a new PR for changes , u can update within this from next time

**Comment by Sanju-github002** [comment]
> @Sanju-github002 u always don't need to make a new PR for changes , u can update within this from next time

Yaaa maam sorry but I don't know this 😅 next time I will take care of this.

**Pull request closed without merging**
