### PR TITLE
Updated Game-Zone Page 

### LINKED ISSUE #75: Correct the game zone page and add some new features
## Issue Type:

- [x] Bug Report
- [x] Feature Request
- [x] Documentation

## **Describe the bug**

The game zone page content is not placed well. And even more features can be added to the pages.

## **Possible solution**

I will place all content of game zone page well and will add more features to it. And will also add new features to other pages like footer, scroll top arrow.

## **Screenshots**

Screenshot (790)

### PR DESCRIPTION
**Pull request by sr-sweta**
# Description

Corrected the view of Game-Zone page. Added some visual effects using AOS library and footer also.
Fixes #75 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Text-editors used:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Screenshot (794)

Screenshot (795)

### CODE REVIEW

**Comment by arpit456jain** [comment]
@sr-sweta please resolve these merge conflicts

**Comment by sr-sweta** [comment]
> @sr-sweta please resolve these merge conflicts

@arpit456jain Can you please tell me what is creating conflict? Or what should I do? Because I have never faced any conflict in any of my PRs before.

**Comment by arpit456jain** [comment]
@ankitapuri please help

**Comment by ankitapuri** [comment]
@sr-sweta just merge the conflicting files in your branch and then add the code accordingly

**Comment by arpit456jain** [comment]
@sr-sweta I had resolved the merge conflicts this time kindly go through some you tube videos for learning how to resolve these merge conflicts .

**Comment by sr-sweta** [comment]
> @sr-sweta I had resolved the merge conflicts this time kindly go through some you tube videos for learning how to resolve these merge conflicts .
> https://www.youtube.com/watch?v=JtIX3HJKwfo
Thank you so much

**Comment by arpit456jain** [comment]
dont't worry @sr-sweta its working fine have a look 

https://deploy-preview-102--cool-front-end-templates.netlify.app/game%20zone/source.html

**Pull request merged**
